name: Deploy NestJS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Build Image
        run: docker compose build --no-cache

      - name: Stop Container
        shell: pwsh
        run: |
          docker compose down
          if ($LASTEXITCODE -ne 0) {
            Write-Host "Container belum ada, lanjut..."
          }

      - name: Start Container
        run: docker compose up -d

      - name: Remove Unused Images
        run: docker image prune -f
